version: '3.8'

services:
  backend:
    image: scale112/gmb-boost-pro-backend:latest
    container_name: gmb-boost-pro-backend-hub
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/health', (res) => { if (res.statusCode === 200) { process.exit(0) } else { process.exit(1) } })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - gmb-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  gmb-network:
    driver: bridge