version: '3.8'

services:
  backend:
    build: .
    container_name: gmb-boost-pro-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
    env_file:
      - .env
    volumes:
      # Mount source code for development (optional - remove for production)
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/health', (res) => { if (res.statusCode === 200) { process.exit(0) } else { process.exit(1) } })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - gmb-network

networks:
  gmb-network:
    driver: bridge