version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: gmb-boost-pro-backend-new
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      # All credentials are hardcoded in the server.js file
      - GOOGLE_CLIENT_ID=52772597205-9ogv54i6sfvucse3jrqj1nl1hlkspcv1.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - FRONTEND_URL=http://localhost:3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/health', (res) => { if (res.statusCode === 200) { process.exit(0) } else { process.exit(1) } })"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - gmb-network
    # Remove volume mounts for production container
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  gmb-network:
    driver: bridge
    name: gmb-boost-pro-network